name: Deploy Backend From Master
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container to GHCR
        uses: docker/build-push-action@v5
        with:
          context: backend
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/brynghiffar/chatbyte:latest

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: latest
      # - name: Setup SSH key
      #   run: |
      #     mkdir -p ~/.ssh
      #     echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
      #     chmod 600 ~/.ssh/id_ed25519
      #     ssh-keyscan -p ${{ secrets.SSH_PORT || 22 }} ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      #     chmod 600 ~/.ssh/known_hosts
      - name: Deploy Backend
        run: |
          tailscale ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            set -e

            echo "Connected to server. Starting deployment"

            cd chatbyte
            docker compose pull
            docker compose down --remove-orphans
            docker compose up -d

            echo "Deployment finished successfully"
          '
