name: Deploy Backend From Master
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: harbor.bghiffar.com
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build and push container to private registry
        uses: docker/build-push-action@v5
        with:
          context: backend
          platforms: linux/amd64
          push: true
          tags: |
            harbor.bghiffar.com/chatbyte/backend:${{ github.sha }}

      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
          version: latest
      - name: Deploy Backend
        run: |
          tailscale ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "

            set -e

            kubectl set image deployment/chatbyte-backend chatbyte-backend=harbor.bghiffar.com/chatbyte:${{ github.sha }}
          "
