name: Deploy Backend From Master
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # Build backend Container
      
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container to GHCR
        uses: docker/build-push-action@v5
        with:
          context: backend
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/brynghiffar/chatbyte-be:latest

      # - name: Install Tailscale
      #   uses: |
      #     curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.noctilucent.asc | sudo apt-key add -
      #     curl -fsSL https://pkgs.tailscale.com/stable/ubuntu/jammy.noctilucent.list | sudo tee /etc/apt/sources.list.d/tailscale.list
      #     sudo apt-get update
      #     sudo apt-get install -y tailscale
      #
      # - name: Connect to Tailscale Network
      #   uses: |
      #     sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=github-actions-runner --tags=ci-runner --ephemeral --ssh
      #     # Wait for Tailscale to connect and get an IP
      #     sleep 5
      #     tailscale status

